# Generated by Django 5.2.6 on 2026-09-19 16:45

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("market_number", models.CharField(max_length=120)),
                ("contracting_authority", models.CharField(max_length=255)),
                ("subject", models.TextField()),
                ("amount_ht", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("vat_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("date_limite_remise_offres", models.DateField(blank=True, null=True)),
                ("date_ouverture_plis", models.DateField(blank=True, null=True)),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("date_os_commencement", models.DateField(blank=True, null=True)),
                ("contract_duration_value", models.PositiveIntegerField(blank=True, null=True)),
                ("contract_duration_unit", models.CharField(blank=True, choices=[("DAYS", "Jours"), ("MONTHS", "Mois")], max_length=10, null=True)),
                ("formula_structure", models.CharField(choices=[("SINGLE", "Formule unique"), ("MULTIPLE", "Formules multiples")], max_length=10)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archivée")], default="ACTIVE", max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="markets", to="companies.company")),
            ],
            options={"db_table": "markets_market"},
        ),
        migrations.CreateModel(
            name="MarketLot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("lot_number", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("amount_ht", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("market", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lots", to="markets.market")),
            ],
            options={"db_table": "markets_marketlot", "ordering": ["display_order", "lot_number"]},
        ),
        migrations.AddIndex(model_name="market", index=models.Index(fields=["company", "status"], name="markets_mar_company_33834a_idx")),
        migrations.AddIndex(model_name="market", index=models.Index(fields=["market_number"], name="markets_mar_market__7c238f_idx")),
        migrations.AddConstraint(model_name="market", constraint=models.UniqueConstraint(fields=("company", "market_number"), name="uniq_market_company_number")),
        migrations.AddConstraint(model_name="market", constraint=models.CheckConstraint(condition=models.Q(("amount_ht__gte", 0), ("amount_ht__isnull", True), _connector="OR"), name="market_amount_ht_nonnegative")),
        migrations.AddConstraint(model_name="market", constraint=models.CheckConstraint(condition=models.Q(models.Q(("vat_rate__gte", 0), ("vat_rate__lte", 100)), ("vat_rate__isnull", True), _connector="OR"), name="market_vat_rate_range")),
        migrations.AddConstraint(model_name="market", constraint=models.CheckConstraint(condition=models.Q(models.Q(("contract_duration_unit__isnull", True), ("contract_duration_value__isnull", True)), models.Q(("contract_duration_unit__isnull", False), ("contract_duration_value__isnull", False)), _connector="OR"), name="market_duration_pair")),
        migrations.AddIndex(model_name="marketlot", index=models.Index(fields=["market", "display_order", "lot_number"], name="markets_mar_market__a19649_idx")),
        migrations.AddConstraint(model_name="marketlot", constraint=models.UniqueConstraint(fields=("market", "lot_number"), name="uniq_marketlot_market_number")),
        migrations.AddConstraint(model_name="marketlot", constraint=models.CheckConstraint(condition=models.Q(("amount_ht__gte", 0), ("amount_ht__isnull", True), _connector="OR"), name="marketlot_amount_ht_nonnegative")),
    ]
