# Generated by Django 5.2.6 on 2026-09-20 02:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_market_holders_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_groups', to='markets.market')),
            ],
            options={
                'db_table': 'markets_revisiongroup',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MarketFormula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('expression_display', models.CharField(blank=True, max_length=500)),
                ('constant_term', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validée'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('reference_period_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reference_period_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('reference_rule_code', models.CharField(blank=True, max_length=120)),
                ('reference_source', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_market_formulas', to=settings.AUTH_USER_MODEL)),
                ('revision_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='markets.revisiongroup')),
            ],
            options={
                'db_table': 'markets_marketformula',
                'ordering': ['version_number'],
                'indexes': [models.Index(fields=['revision_group', 'status'], name='formula_group_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormulaTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('coefficient', models.DecimalField(decimal_places=8, max_digits=18)),
                ('term_type', models.CharField(choices=[('INDEX_RATIO', 'Ratio d’index')], default='INDEX_RATIO', max_length=40)),
                ('index_code', models.CharField(max_length=120)),
                ('base_period_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('base_period_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('base_value', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('base_source', models.TextField(blank=True)),
                ('reference_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='markets.marketformula')),
            ],
            options={
                'db_table': 'markets_formulaterm',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('formula', 'position'), name='uniq_formulaterm_formula_position'), models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='formulaterm_position_positive'), models.CheckConstraint(condition=models.Q(('base_value__isnull', True), ('base_value__gt', 0), _connector='OR'), name='formulaterm_base_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='revisiongroup',
            constraint=models.UniqueConstraint(fields=('market', 'code'), name='uniq_revisiongroup_market_code'),
        ),
        migrations.AddConstraint(
            model_name='revisiongroup',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '\\S')), name='revisiongroup_code_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='revisiongroup',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='revisiongroup_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='marketformula',
            constraint=models.UniqueConstraint(fields=('revision_group', 'version_number'), name='uniq_marketformula_group_version'),
        ),
        migrations.AddConstraint(
            model_name='marketformula',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gt', 0)), name='marketformula_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='marketformula',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='marketformula_valid_dates_order'),
        ),
    ]
