# Generated by Django 5.2.6 on 2026-09-20 15:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_rc_city'),
        ('markets', '0004_revisiongroup_marketformula_formulaterm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaTemplateTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('coefficient', models.DecimalField(decimal_places=8, max_digits=18)),
                ('term_type', models.CharField(choices=[('INDEX_RATIO', 'Ratio d’index')], default='INDEX_RATIO', max_length=40)),
                ('index_code', models.CharField(max_length=120)),
                ('base_period_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('base_period_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('base_value', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('base_source', models.TextField(blank=True)),
                ('reference_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'markets_formulatemplateterm',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='marketformula',
            name='source_template_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FormulaTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_key', models.UUIDField(default=uuid.uuid4)),
                ('version_number', models.PositiveIntegerField()),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('COMPANY', 'Société')], default='GLOBAL', max_length=20)),
                ('code', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=120)),
                ('expression_display', models.CharField(blank=True, max_length=500)),
                ('constant_term', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VERIFIED', 'Vérifié'), ('DEPRECATED', 'Déprécié')], default='DRAFT', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('OFFICIAL', 'Officielle'), ('CONTRACT_EXAMPLE', 'Exemple contractuel'), ('INTERNAL', 'Interne')], max_length=30)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=80)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formula_templates', to='companies.company')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_formula_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'markets_formulatemplate',
                'ordering': ['code', 'version_number'],
            },
        ),
        migrations.AddField(
            model_name='marketformula',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_copies', to='markets.formulatemplate'),
        ),
        migrations.AddConstraint(
            model_name='marketformula',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_template__isnull', True), ('source_template_version__isnull', True)), models.Q(('source_template__isnull', False), ('source_template_version__isnull', False)), _connector='OR'), name='marketformula_source_template_pair'),
        ),
        migrations.AddField(
            model_name='formulatemplateterm',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='markets.formulatemplate'),
        ),
        migrations.AddIndex(
            model_name='formulatemplate',
            index=models.Index(fields=['scope', 'status', 'code'], name='template_scope_status_code_idx'),
        ),
        migrations.AddIndex(
            model_name='formulatemplate',
            index=models.Index(fields=['family_key', 'version_number'], name='template_family_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='formulatemplate',
            constraint=models.UniqueConstraint(fields=('family_key', 'version_number'), name='uniq_formulatemplate_family_version'),
        ),
        migrations.AddConstraint(
            model_name='formulatemplate',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gt', 0)), name='formulatemplate_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='formulatemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_company__isnull', True), ('scope', 'GLOBAL')), models.Q(('owner_company__isnull', False), ('scope', 'COMPANY')), _connector='OR'), name='formulatemplate_scope_owner_consistent'),
        ),
        migrations.AddConstraint(
            model_name='formulatemplate',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='formulatemplate_valid_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='formulatemplateterm',
            constraint=models.UniqueConstraint(fields=('template', 'position'), name='uniq_template_term_position'),
        ),
        migrations.AddConstraint(
            model_name='formulatemplateterm',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='template_term_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='formulatemplateterm',
            constraint=models.CheckConstraint(condition=models.Q(('base_value__isnull', True), ('base_value__gt', 0), _connector='OR'), name='template_term_base_positive'),
        ),
    ]
