# Generated by Django 5.2.6 on 2026-09-20 18:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0001_initial'),
        ('companies', '0002_company_rc_city'),
        ('consortia', '0002_consortium_invariants'),
        ('markets', '0005_formulatemplateterm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_number', models.CharField(max_length=120)),
                ('designation', models.TextField()),
                ('unit', models.CharField(max_length=80)),
                ('estimated_quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price_ht', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estimated_amount_ht', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('classification_status', models.CharField(choices=[('PENDING_CLASSIFICATION', 'À classer'), ('REVISABLE', 'Révisable'), ('NON_REVISABLE', 'Sans révision')], default='PENDING_CLASSIFICATION', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'markets_priceitem',
                'ordering': ['price_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Saisie manuelle'), ('IMPORT', 'Import')], default='MANUAL', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('change_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'markets_priceschedule',
            },
        ),
        migrations.AddField(
            model_name='market',
            name='global_revision_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='global_markets', to='markets.revisiongroup'),
        ),
        migrations.AddField(
            model_name='market',
            name='revision_application_mode',
            field=models.CharField(choices=[('GLOBAL_FORMULA', "Une seule formule pour l'ensemble du marché"), ('PRICE_ASSIGNMENT', 'Affectation des formules prix par prix')], default='PRICE_ASSIGNMENT', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('global_revision_group__isnull', False), ('revision_application_mode', 'GLOBAL_FORMULA')), models.Q(('global_revision_group__isnull', True), ('revision_application_mode', 'PRICE_ASSIGNMENT')), _connector='OR'), name='market_revision_mode_group_consistent'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_items', to='markets.marketlot'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='revision_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_items', to='markets.revisiongroup'),
        ),
        migrations.AddField(
            model_name='priceschedule',
            name='market',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='price_schedule', to='markets.market'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='price_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='markets.priceschedule'),
        ),
        migrations.AddConstraint(
            model_name='priceschedule',
            constraint=models.CheckConstraint(condition=models.Q(('change_version__gt', 0)), name='priceschedule_change_version_positive'),
        ),
        migrations.AddIndex(
            model_name='priceitem',
            index=models.Index(fields=['price_schedule', 'classification_status'], name='markets_pri_price_s_d84ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='priceitem',
            index=models.Index(fields=['price_schedule', 'revision_group'], name='markets_pri_price_s_d8aad7_idx'),
        ),
        migrations.AddIndex(
            model_name='priceitem',
            index=models.Index(fields=['lot', 'active'], name='markets_pri_lot_id_c8f8da_idx'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.UniqueConstraint(fields=('price_schedule', 'price_number'), name='uniq_priceitem_schedule_number'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_number__regex', '\\S')), name='priceitem_number_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.CheckConstraint(condition=models.Q(('designation__regex', '\\S')), name='priceitem_designation_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit__regex', '\\S')), name='priceitem_unit_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_quantity__gte', 0)), name='priceitem_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_ht__gte', 0)), name='priceitem_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_amount_ht__gte', 0)), name='priceitem_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('classification_status', 'REVISABLE'), ('revision_group__isnull', False)), models.Q(('classification_status__in', ['PENDING_CLASSIFICATION', 'NON_REVISABLE']), ('revision_group__isnull', True)), _connector='OR'), name='priceitem_classification_assignment_consistent'),
        ),
    ]
