# Generated by Django 5.2.6 on 2026-09-21 23:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_index_reference_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('detected_periods', models.JSONField(default=list)),
                ('source_reference', models.CharField(max_length=1000)),
                ('extraction_method', models.CharField(choices=[('NATIVE_TEXT', 'Texte natif'), ('TABLE_EXTRACTION', 'Extraction de tableau'), ('OCR', 'OCR'), ('MANUAL_REVIEW_REQUIRED', 'Revue manuelle requise')], max_length=32)),
                ('extraction_status', models.CharField(choices=[('PROCESSED', 'Traité'), ('PENDING_VALIDATION', 'Validation en attente'), ('ERROR', 'Erreur')], max_length=32)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'markets_indexsourcedocument',
                'ordering': ['original_filename'],
            },
        ),
        migrations.CreateModel(
            name='RawIndexExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_code', models.CharField(blank=True, max_length=120)),
                ('raw_designation', models.TextField(blank=True)),
                ('raw_value', models.CharField(blank=True, max_length=120)),
                ('source_column', models.CharField(blank=True, max_length=40)),
                ('raw_status', models.CharField(blank=True, max_length=40)),
                ('extraction_method', models.CharField(choices=[('NATIVE_TEXT', 'Texte natif'), ('TABLE_EXTRACTION', 'Extraction de tableau'), ('OCR', 'OCR'), ('MANUAL_REVIEW_REQUIRED', 'Revue manuelle requise')], max_length=32)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('ambiguity', models.TextField(blank=True)),
                ('normalized_code', models.CharField(blank=True, max_length=120)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('validation_status', models.CharField(default='PENDING_VALIDATION', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_extractions', to='markets.indexsourcedocument')),
            ],
            options={
                'db_table': 'markets_rawindexextraction',
                'indexes': [models.Index(fields=['source_document', 'page_number'], name='raw_index_doc_page_idx')],
            },
        ),
    ]
