# Generated by Django 5.2.6 on 2026-10-01 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0015_statement_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDiscoveryCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_page_url', models.URLField(max_length=500)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OFFICIAL_SOURCE_UNAVAILABLE', 'Source officielle indisponible')], max_length=40)),
                ('new_documents_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'markets_officialdiscoverycheck',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='indexpublication',
            name='uniq_indexpublication_period_source',
        ),
        migrations.AddField(
            model_name='indexpublication',
            name='import_method',
            field=models.CharField(choices=[('MANUAL', 'Import manuel'), ('OFFICIAL_AUTO', 'Découverte officielle')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='indexpublication',
            name='source_page_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='indexpublication',
            name='source_pdf_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='indexpublication',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='index_publications_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indexsourcedocument',
            name='import_method',
            field=models.CharField(choices=[('MANUAL', 'Import manuel'), ('OFFICIAL_AUTO', 'Découverte officielle')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='indexsourcedocument',
            name='source_page_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='indexsourcedocument',
            name='source_pdf_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='indexsourcedocument',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexsourcedocument',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='index_documents_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indexsourcedocument',
            name='validation_status',
            field=models.CharField(default='PENDING_VALIDATION', max_length=32),
        ),
        migrations.AddField(
            model_name='officialdiscoverycheck',
            name='latest_new_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discovery_checks', to='markets.indexsourcedocument'),
        ),
    ]
