# Generated by Django 5.2.6 on 2026-10-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0016_officialdiscoverycheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexsourcedocument',
            name='stored_file',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
