import { FormEvent, useEffect, useState } from 'react'
import { ApiError, MarketLot, saveMarketLot } from '../lib/api'

type Props = { marketId: string; lot?: MarketLot; onSaved: (lot: MarketLot) => void }

export function MarketLotForm({ marketId, lot, onSaved }: Props) {
  const [values, setValues] = useState({ lot_number: lot?.lot_number ?? '', title: lot?.title ?? '', description: lot?.description ?? '', amount_ht: lot?.amount_ht ?? '', display_order: String(lot?.display_order ?? 0), active: lot?.active ?? true, notes: lot?.notes ?? '' })
  const [errors, setErrors] = useState<Record<string, string[]>>({}); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => setValues({ lot_number: lot?.lot_number ?? '', title: lot?.title ?? '', description: lot?.description ?? '', amount_ht: lot?.amount_ht ?? '', display_order: String(lot?.display_order ?? 0), active: lot?.active ?? true, notes: lot?.notes ?? '' }), [lot])
  const update = (key: string, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setErrors({}); setLoading(true); try { onSaved(await saveMarketLot({ ...values, amount_ht: values.amount_ht === '' ? null : values.amount_ht, display_order: Number(values.display_order) }, marketId, lot?.id)) } catch (caught) { if (caught instanceof ApiError) { setError(caught.payload.message); setErrors(caught.payload.fields ?? {}) } else setError('Enregistrement impossible.') } finally { setLoading(false) } }
  return <form className="card company-form" onSubmit={submit}>{error && <div className="alert error" role="alert">{error}</div>}<div className="form-grid"><label>Numéro du lot<input value={values.lot_number} onChange={(e) => update('lot_number', e.target.value)} required />{errors.lot_number && <small className="field-error">{errors.lot_number.join(' ')}</small>}</label><label>Titre<input value={values.title} onChange={(e) => update('title', e.target.value)} required />{errors.title && <small className="field-error">{errors.title.join(' ')}</small>}</label></div><label>Description<textarea value={values.description} onChange={(e) => update('description', e.target.value)} /></label><div className="form-grid"><label>Montant HT<input type="number" min="0" step="0.01" value={values.amount_ht} onChange={(e) => update('amount_ht', e.target.value)} />{errors.amount_ht && <small className="field-error">{errors.amount_ht.join(' ')}</small>}</label><label>Ordre d'affichage<input type="number" min="0" step="1" value={values.display_order} onChange={(e) => update('display_order', e.target.value)} />{errors.display_order && <small className="field-error">{errors.display_order.join(' ')}</small>}</label></div><label className="checkbox-label"><input type="checkbox" checked={values.active} onChange={(e) => update('active', e.target.checked)} /> Lot actif</label><label>Notes<textarea value={values.notes} onChange={(e) => update('notes', e.target.value)} /></label><div className="form-actions"><button type="submit" className="primary" disabled={loading}>{loading ? 'Enregistrement…' : lot ? 'Enregistrer' : 'Ajouter le lot'}</button></div></form>
}
