import { useEffect, useState } from 'react'
import { ApiError, FormulaTemplate, MarketFormula, RevisionGroup, copyFormulaTemplate, listFormulaTemplates, listRevisionGroups, saveMarketFormula, saveRevisionGroup } from '../lib/api'

type Props = { marketId: string; role: string | null | undefined }
const canEdit = (role: string | null | undefined) => role === 'OWNER' || role === 'ADMIN'
const errorMessage = (error: unknown) => error instanceof ApiError ? error.payload.message : 'Erreur réseau. Réessayez.'
const sourceLabel = (template: FormulaTemplate) => template.source_title || template.source_reference || template.source_type
function complement(value: string) {
  const normalized = value.replace(',', '.').trim(); if (!/^\d+(\.\d+)?$/.test(normalized)) return ''
  const [integer, fraction = ''] = normalized.split('.'); const scale = Math.max(fraction.length, 8); const unit = 10n ** BigInt(scale); const number = BigInt(integer) * unit + BigInt(fraction.padEnd(scale, '0')); const result = unit - number; const text = result.toString().padStart(scale + 1, '0'); return `${text.slice(0, -scale)}.${text.slice(-scale)}`
}

function FormulaEditor({ marketId, group, formula, onSaved, onCancel }: { marketId: string; group: RevisionGroup; formula: MarketFormula; onSaved: () => void; onCancel: () => void }) {
  const [constant, setConstant] = useState(formula.constant_term ?? ''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const variable = formula.terms.length === 1 ? complement(constant) : ''
  const save = async (status: 'DRAFT' | 'VALIDATED') => { setSaving(true); setError(''); try { await saveMarketFormula(marketId, group.id, { constant_term: constant || null, status, terms: formula.terms.map((term, index) => ({ position: index + 1, coefficient: index === 0 && variable ? variable : term.coefficient, term_type: term.term_type, index_code: term.index_code, base_period_year: term.base_period_year, base_period_month: term.base_period_month, base_value: term.base_value, base_source: term.base_source, reference_note: term.reference_note })) }, formula.id); onSaved() } catch (caught) { setError(errorMessage(caught)) } finally { setSaving(false) } }
  return <div className="card company-form"><h3>Formule de révision</h3>{error && <div className="alert error" role="alert">{error}</div>}<label>Partie fixe<input aria-label="Partie fixe" value={constant} disabled={formula.status !== 'DRAFT' || saving} inputMode="decimal" onChange={(event) => setConstant(event.target.value)} /></label>{formula.terms.length === 1 && <p>Partie variable calculée : {variable || '—'}</p>}<div className="inline-actions"><button className="primary" disabled={saving || formula.status !== 'DRAFT'} onClick={() => void save('DRAFT')}>Enregistrer</button>{formula.status === 'DRAFT' && <button className="secondary" disabled={saving} onClick={() => void save('VALIDATED')}>Valider</button>}<button className="link-button" onClick={onCancel}>Annuler</button></div></div>
}

function TemplatePicker({ marketId, group, editable, onCopied, onCancel }: { marketId: string; group: RevisionGroup; editable: boolean; onCopied: () => void; onCancel: () => void }) {
  const [templates, setTemplates] = useState<FormulaTemplate[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [copying, setCopying] = useState(''); const [error, setError] = useState('')
  const load = () => { setLoading(true); listFormulaTemplates(query).then(setTemplates).catch((caught) => setError(errorMessage(caught))).finally(() => setLoading(false)) }
  useEffect(() => { load() }, [])
  const copy = async (template: FormulaTemplate) => { setCopying(template.id); try { await copyFormulaTemplate(marketId, group.id, template.id); onCopied() } catch (caught) { setError(errorMessage(caught)) } finally { setCopying('') } }
  return <div className="card company-form" aria-label="Bibliothèque des modèles"><h3>Choisir une formule de révision</h3><p className="muted">Vérifiez que cette formule correspond au CPS de votre marché.</p>{error && <div className="alert error" role="alert">{error}</div>}<div className="inline-actions"><input aria-label="Rechercher un modèle" placeholder="Rechercher" value={query} onChange={(event) => setQuery(event.target.value)} /><button type="button" className="secondary" onClick={load}>Rechercher</button></div>{loading ? <p className="state">Chargement…</p> : templates.length === 0 ? <div className="state">Aucun modèle GLOBAL disponible.</div> : <div>{templates.map((template) => <article className="formula-card" key={template.id}><div className="inline-actions"><strong>{template.designation}</strong><span className="badge">{template.status}</span><span>Version {template.version_number}</span></div><p>{template.expression_display || 'Expression non renseignée'}</p><p className="muted">Source : {sourceLabel(template)}</p>{editable ? <button type="button" className="primary" disabled={copying === template.id || template.status !== 'VERIFIED'} onClick={() => void copy(template)}>{copying === template.id ? 'Copie…' : template.status === 'VERIFIED' ? 'Sélectionner cette formule' : 'Non disponible'}</button> : <span className="muted">Lecture seule</span>}</article>)}</div>}<button type="button" className="link-button" onClick={onCancel}>Annuler</button></div>
}

export function RevisionFormulaSection({ marketId, role }: Props) {
  const [groups, setGroups] = useState<RevisionGroup[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [templateGroup, setTemplateGroup] = useState<RevisionGroup | null>(null); const [editing, setEditing] = useState<{ group: RevisionGroup; formula: MarketFormula } | null>(null); const [newFormula, setNewFormula] = useState(false); const [label, setLabel] = useState('')
  const editable = canEdit(role)
  const load = () => { setLoading(true); listRevisionGroups(marketId).then(setGroups).catch((caught) => setError(errorMessage(caught))).finally(() => setLoading(false)) }
  useEffect(() => { load() }, [marketId])
  const createFormula = async () => { try { const created = await saveRevisionGroup(marketId, { code: `FORMULA-${crypto.randomUUID().slice(0, 8)}`, name: label || 'Formule de révision', sort_order: groups.length }); setGroups((current) => [...current, created]); setLabel(''); setNewFormula(false); setTemplateGroup(created) } catch (caught) { setError(errorMessage(caught)) } }
  if (loading) return <section><div className="section-heading"><h2>Formules de révision</h2></div><p className="state">Chargement…</p></section>
  return <section aria-label="Formules de révision"><div className="section-heading"><div><p className="eyebrow">STRUCTURE CONTRACTUELLE</p><h2>Formules de révision</h2></div>{editable && <button className="primary" onClick={() => setNewFormula(true)}>Ajouter une formule de révision</button>}</div>{error && <div className="alert error" role="alert">{error}<button className="link-button" onClick={load}>Réessayer</button></div>}{newFormula && <div className="card company-form"><label>Nom de la formule<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Formule de révision" /></label><div className="inline-actions"><button className="primary" type="button" onClick={() => void createFormula()}>Choisir dans la bibliothèque</button><button className="link-button" type="button" onClick={() => setNewFormula(false)}>Annuler</button></div></div>}{groups.length === 0 && !newFormula ? <div className="card state">Aucune formule de révision n’est enregistrée.</div> : groups.map((group) => <div className="card" key={group.id}><div className="section-heading"><h3>{group.name}</h3><button className="secondary" onClick={() => setTemplateGroup(group)}>{editable ? 'Choisir une formule' : 'Consulter les formules'}</button></div>{group.formulas.length === 0 && <p className="muted">Aucune formule sélectionnée.</p>}{group.formulas.map((formula: MarketFormula) => <div className="formula-card" key={formula.id}><div className="inline-actions"><strong>{formula.label}</strong><span className={`badge ${formula.status.toLowerCase()}`}>{formula.status === 'DRAFT' ? 'Brouillon' : formula.status === 'VALIDATED' ? 'Validée' : 'Inactive'}</span></div>{formula.expression_display && <p>{formula.expression_display}</p>}<p>Partie fixe : {formula.constant_term ?? '—'}</p>{formula.terms.length === 1 && <p>Partie variable calculée : {formula.terms[0].coefficient}</p>}{editable && formula.status === 'DRAFT' && <button className="secondary" onClick={() => setEditing({ group, formula })}>Modifier</button>}</div>)}</div>)}{templateGroup && <TemplatePicker marketId={marketId} group={templateGroup} editable={editable} onCopied={() => { setTemplateGroup(null); load() }} onCancel={() => setTemplateGroup(null)} />}{editing && <FormulaEditor marketId={marketId} group={editing.group} formula={editing.formula} onSaved={() => { setEditing(null); load() }} onCancel={() => setEditing(null)} />}</section>
}
