import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { ApiError, getStatementCalculation, listMonthlyWorkAllocations, listStatements, MonthlyWorkAllocation, Market, saveMonthlyWorkAllocation, saveStatement, Statement, StatementCalculation } from '../lib/api'
import { formatMoney } from '../lib/formatters'

function message(error: unknown) { return error instanceof ApiError ? error.payload.message : 'Erreur réseau. Réessayez.' }
const calculationStatusLabel: Record<string, string> = { CALCULABLE_PREVIEW: 'Calcul calculable', INDEX_NOT_AVAILABLE: 'Index non disponible', PENDING_INDEX: 'Validation de l’indice en attente', FORMULA_NOT_AVAILABLE: 'Formule non disponible', FORMULA_NOT_SUPPORTED_V1: 'Formule non prise en charge', NO_WORK_DAYS: 'Aucun jour de travaux' }
function revisionLabel(row: StatementCalculation['monthly_results'][number]) { if (row.revision_amount !== null) return formatMoney(row.revision_amount); return row.calculation_status === 'PENDING_INDEX' || row.index_status === 'PENDING_VALIDATION' ? 'Validation de l’indice en attente' : 'Index non disponible' }
function monthLabel(year: number, month: number) { return new Intl.DateTimeFormat('fr-FR', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(Date.UTC(year, month - 1, 1))) }
function monthsBetween(start: string | null, end: string) {
  const first = start ? new Date(`${start.slice(0, 7)}-01T00:00:00Z`) : new Date(`${end.slice(0, 7)}-01T00:00:00Z`)
  const last = new Date(`${end.slice(0, 7)}-01T00:00:00Z`); const months: Array<{ year: number; month: number }> = []
  for (const cursor = new Date(first); cursor <= last; cursor.setUTCMonth(cursor.getUTCMonth() + 1)) months.push({ year: cursor.getUTCFullYear(), month: cursor.getUTCMonth() + 1 })
  return months
}

export function StatementSection({ market, editable }: { market: Market; editable: boolean }) {
  const [statements, setStatements] = useState<Statement[]>([]); const [selected, setSelected] = useState<Statement | null>(null); const [allocations, setAllocations] = useState<MonthlyWorkAllocation[]>([]); const [calculation, setCalculation] = useState<StatementCalculation | null>(null); const [creating, setCreating] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const [form, setForm] = useState({ number: '1', date: new Date().toISOString().slice(0, 10), amount_ht: '', observation: '' })
  const load = async () => { try { const loaded = await listStatements(market.id); setStatements(loaded); if (loaded.length && !selected) await select(loaded[0]) } catch (caught) { setError(message(caught)) } }
  const select = async (statement: Statement) => { setError(''); setSelected(statement); setCalculation(null); try { const loaded = await listMonthlyWorkAllocations(market.id, statement.id); setAllocations(loaded) } catch (caught) { setError(message(caught)) } }
  useEffect(() => { void load() }, [market.id])
  const totalDays = useMemo(() => allocations.reduce((sum, item) => sum + Number(item.work_days), 0), [allocations])
  const createStatement = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const statement = await saveStatement(market.id, form); setStatements((current) => [...current, statement].sort((a, b) => a.number - b.number)); setCreating(false); await select(statement); setForm((current) => ({ ...current, number: String(statement.number + 1), amount_ht: '' })) } catch (caught) { setError(message(caught)) } finally { setBusy(false) } }
  const addRequiredMonths = () => { if (!selected) return; const wanted = monthsBetween(market.date_os_commencement, selected.date); setAllocations((current) => wanted.map((item) => current.find((row) => row.year === item.year && row.month === item.month) || { id: `new-${item.year}-${item.month}`, statement: selected.id, year: item.year, month: item.month, work_days: '0', created_at: '', updated_at: '' })) }
  const saveAllocations = async () => { if (!selected) return; setBusy(true); setError(''); try { const saved = []; for (const item of allocations) saved.push(await saveMonthlyWorkAllocation(market.id, selected.id, { year: item.year, month: item.month, work_days: item.work_days }, item.id.startsWith('new-') ? undefined : item.id)); setAllocations(saved); setCalculation(null) } catch (caught) { setError(message(caught)) } finally { setBusy(false) } }
  const calculate = async () => { if (!selected) return; setBusy(true); setError(''); try { setCalculation(await getStatementCalculation(market.id, selected.id)) } catch (caught) { setError(message(caught)) } finally { setBusy(false) } }

  return <section className="statements-section"><div className="section-heading"><div><p className="eyebrow">DÉCOMPTES</p><h2>Décomptes simples</h2></div>{editable && <button className="primary" type="button" onClick={() => setCreating(true)}>+ Nouveau décompte</button>}</div>{error && <div className="alert error">{error}</div>}
    {creating && <form className="card company-form" onSubmit={createStatement}><div className="form-grid"><label>N° décompte<input type="number" min="1" value={form.number} onChange={(event) => setForm({ ...form, number: event.target.value })} required /></label><label>Date<input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} required /></label><label>Montant HT<input inputMode="decimal" value={form.amount_ht} onChange={(event) => setForm({ ...form, amount_ht: event.target.value })} required /></label><label>Observation<textarea value={form.observation} onChange={(event) => setForm({ ...form, observation: event.target.value })} /></label></div><div className="inline-actions"><button className="primary" disabled={busy}>Créer</button><button className="secondary" type="button" onClick={() => setCreating(false)}>Annuler</button></div></form>}
    {statements.length === 0 ? <div className="card state">Aucun décompte. Aucun BDP, lot ou article n'est nécessaire pour ce parcours V1.</div> : <div className="company-list">{statements.map((statement) => <button className={`card company-row statement-row ${selected?.id === statement.id ? 'selected' : ''}`} type="button" key={statement.id} onClick={() => void select(statement)}><div><strong>Décompte n°{statement.number}</strong><span>{statement.date} · {statement.observation || 'Sans observation'}</span></div><div><strong>{formatMoney(statement.amount_ht)} HT</strong><span>{selected?.id === statement.id ? `${totalDays} jour(s)` : 'Voir la répartition'}</span><span className="badge">PREVIEW</span></div></button>)}</div>}
    {selected && <div className="card allocation-card"><div className="section-heading"><div><p className="eyebrow">RÉPARTITION DES TRAVAUX</p><h3>Décompte n°{selected.number} — {formatMoney(selected.amount_ht)} HT</h3></div><div className="inline-actions"><button className="secondary" type="button" onClick={addRequiredMonths}>Afficher les mois OS → décompte</button>{editable && <button className="primary" type="button" disabled={busy || allocations.length === 0} onClick={() => void saveAllocations()}>Enregistrer les jours</button>}</div></div>{allocations.length === 0 ? <p className="state">Ajoutez les mois nécessaires à la note de calcul.</p> : <div className="table-scroll"><table><thead><tr><th>Mois</th><th>Nombre de jours</th></tr></thead><tbody>{allocations.map((item, index) => <tr key={item.id}><td>{monthLabel(item.year, item.month)}</td><td><input aria-label={`Jours ${monthLabel(item.year, item.month)}`} inputMode="decimal" value={item.work_days} disabled={!editable} onChange={(event) => setAllocations((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, work_days: event.target.value } : row))} /></td></tr>)}</tbody><tfoot><tr><th>Total</th><th>{totalDays} jour(s)</th></tr></tfoot></table></div>}{editable && <button className="primary" type="button" disabled={busy || allocations.length === 0} onClick={() => void calculate()}>Calculer la note de calcul</button>}
      {calculation && <CalculationNote calculation={calculation} market={market} statement={selected} />}</div>}
  </section>
}

function CalculationNote({ calculation, market, statement }: { calculation: StatementCalculation; market: Market; statement: Statement }) {
  return <div className="calculation-note"><div className="section-heading"><div><p className="eyebrow">NOTE DE CALCUL DE LA RÉVISION DES PRIX</p><h3>{market.market_number}</h3><span>{market.subject}</span></div><span className={`badge ${calculation.calculation_status === 'CALCULABLE_PREVIEW' ? 'success' : 'warning'}`}>{calculationStatusLabel[calculation.calculation_status] || 'Résultat à vérifier'}</span></div><p><strong>Décompte :</strong> n°{statement.number} · {statement.date} · <strong>Montant travaux HT :</strong> {formatMoney(statement.amount_ht)}</p><p><strong>Mois de base :</strong> {market.date_limite_remise_offres ? market.date_limite_remise_offres.slice(0, 7) : '—'} · <strong>Indice de base :</strong> {calculation.base_index ?? 'Index non disponible'} · <strong>OS :</strong> {market.date_os_commencement ?? '—'}</p><div className="table-scroll"><table><thead><tr><th>Mois</th><th>Jours</th><th>Indice</th><th>I / I0</th><th>Terme variable</th><th>P / P0</th><th>P / P0 - 1</th><th>Montant à réviser</th><th>Montant révision</th></tr></thead><tbody>{calculation.monthly_results.map((row) => <tr key={`${row.year}-${row.month}`}><td>{monthLabel(row.year, row.month)}</td><td>{row.work_days}</td><td>{row.current_index ?? 'Index non disponible'}</td><td>{row.ratio ?? '—'}</td><td>{row.K_minus_1 ?? '—'}</td><td>{row.K ?? '—'}</td><td>{row.K_minus_1 ?? '—'}</td><td>{formatMoney(row.amount_to_revise)}</td><td>{revisionLabel(row)}</td></tr>)}</tbody></table></div><p><strong>Total jours :</strong> {calculation.total_work_days} · <strong>Total montant à réviser :</strong> {formatMoney(calculation.total_allocated_amount)} · <strong>Total révision :</strong> {calculation.total_revision === null ? 'Non finalisable' : formatMoney(calculation.total_revision)}</p><p className="muted">Arrondi réglementaire : {calculation.rounding_status}. Cette sortie est une PREVIEW recalculable, sans RevisionSnapshot validé.</p></div>
}
