import { useEffect, useRef, useState } from 'react'
import { ApiError, IndexDefinition, IndexPublication, MonthlyIndexValue, MonthlyIndexValuePage, OfficialDiscoveryStatus, OfficialImportPreview, checkOfficialPublications, createOfficialIndexDefinition, getOfficialDiscoveryStatus, importOfficialBareme, listIndexDefinitions, listIndexPublications, listIndexValues, resolveOfficialImportRow, validateOfficialBareme } from '../lib/api'

const monthLabel = (year: number, month: number) => new Intl.DateTimeFormat('fr-FR', { month: 'long', year: 'numeric' }).format(new Date(Date.UTC(year, month - 1, 1)))
const formatDecimal = (value: string) => { const negative = value.startsWith('-'); const unsigned = negative ? value.slice(1) : value; const [integer, fraction = ''] = unsigned.split('.'); const grouped = integer.replace(/\B(?=(\d{3})+(?!\d))/g, ' '); const usefulFraction = fraction.replace(/0+$/, '') || '0'; return `${negative ? '-' : ''}${grouped},${usefulFraction}` }
const statusLabel: Record<string, string> = { DEFINITIVE: 'Définitif', PROVISIONAL: 'Provisoire', PENDING_VALIDATION: 'En attente de validation' }
const methodLabel: Record<string, string> = { MANUAL: 'MANUEL', OFFICIAL_AUTO: 'OFFICIEL AUTOMATIQUE' }

export function IndicesPage() {
  const [values, setValues] = useState<MonthlyIndexValue[]>([]); const [pageInfo, setPageInfo] = useState<MonthlyIndexValuePage>({ results: [], count: 0, page: 1, page_size: 50, has_next: false, has_previous: false })
  const [definitions, setDefinitions] = useState<IndexDefinition[]>([]); const [publications, setPublications] = useState<IndexPublication[]>([])
  const [year, setYear] = useState(''); const [month, setMonth] = useState(''); const [code, setCode] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1)
  const [discovery, setDiscovery] = useState<OfficialDiscoveryStatus>({ status: 'NOT_CHECKED', checked_at: null, new_documents: 0, latest_new_document: null })
  const [preview, setPreview] = useState<OfficialImportPreview | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const fileRef = useRef<HTMLInputElement>(null)
  const [details, setDetails] = useState<string | null>(null)
  const [newDesignations, setNewDesignations] = useState<Record<string, string>>({})
  const [correctedCodes, setCorrectedCodes] = useState<Record<string, string>>({})
  const load = (requestedPage = page) => { const params = new URLSearchParams(); if (year) params.set('year', year); if (month) params.set('month', month); if (code) params.set('code', code); if (status) params.set('status', status); params.set('page', String(requestedPage)); params.set('page_size', '50'); Promise.all([listIndexValues(params.toString()), listIndexDefinitions(code), listIndexPublications(), getOfficialDiscoveryStatus()]).then(([loaded, loadedDefinitions, loadedPublications, loadedDiscovery]) => { setPageInfo(loaded); setValues(loaded.results); setDefinitions(loadedDefinitions); setPublications(loadedPublications); setDiscovery(loadedDiscovery); setPage(loaded.page) }).catch((caught) => setError(caught instanceof ApiError ? caught.payload.message : 'Erreur réseau.')) }
  useEffect(() => { load(1) }, [])
  const selectFile = async (file?: File) => { if (!file) return; setBusy(true); setError(''); try { const result = await importOfficialBareme(file); setPreview(result.preview) } catch (caught) { setError(caught instanceof ApiError ? caught.payload.message : 'Import impossible.') } finally { setBusy(false) } }
  const discover = async () => { setBusy(true); setError(''); try { setDiscovery(await checkOfficialPublications()); load(1) } catch (caught) { setError(caught instanceof ApiError ? caught.payload.message : 'Vérification impossible.') } finally { setBusy(false) } }
  const validate = async () => { if (!preview) return; setBusy(true); try { setPreview(await validateOfficialBareme(preview.document_id)); load(1) } catch (caught) { setError(caught instanceof ApiError ? caught.payload.message : 'Validation impossible.') } finally { setBusy(false) } }
  const resolveRow = async (rowId: string, definition: string) => { if (!preview || !definition) return; setBusy(true); setError(''); try { setPreview(await resolveOfficialImportRow(preview.document_id, rowId, definition)) } catch (caught) { setError(caught instanceof ApiError ? caught.payload.message : 'Résolution impossible.') } finally { setBusy(false) } }
  const createDefinition = async (rowId: string, code = '') => { if (!preview) return; setBusy(true); setError(''); try { setPreview(await createOfficialIndexDefinition(preview.document_id, rowId, newDesignations[rowId] || '', code)) } catch (caught) { setError(caught instanceof ApiError ? caught.payload.message : 'Création impossible.') } finally { setBusy(false) } }
  const years = Array.from(new Set(publications.map((item) => item.year))).sort((left, right) => right - left)
  return <section>
    <div className="page-heading"><div><p className="eyebrow">RÉFÉRENTIEL OFFICIEL</p><h1>BASE DES INDICES</h1><p className="muted">Toutes les valeurs affichées proviennent de PostgreSQL. Les PDF servent uniquement à l’import et à l’audit.</p></div><div className="form-actions"><button className="primary" type="button" disabled={busy} onClick={() => fileRef.current?.click()}>Importer un barème officiel</button><button type="button" disabled={busy} onClick={discover}>Vérifier les nouvelles publications</button><input ref={fileRef} hidden type="file" accept="application/pdf,.pdf" onChange={(event) => selectFile(event.target.files?.[0])} /></div></div>
    {error && <div className="alert error">{error}</div>}
    <div className="card"><strong>Source officielle : Ministère de l'Équipement</strong><span className="muted"> · État : {discovery.status === 'OFFICIAL_SOURCE_UNAVAILABLE' ? 'Indisponible' : discovery.status === 'NOT_CHECKED' ? 'Non vérifiée' : 'Disponible'} · Dernière vérification : {discovery.checked_at ? new Date(discovery.checked_at).toLocaleString('fr-FR') : '—'}</span></div>
    <div className="card company-form"><div className="form-grid"><label>Indice<select aria-label="Indice" value={code} onChange={(event) => { setCode(event.target.value); setPage(1) }}><option value="">Tous les indices</option>{definitions.map((item) => <option key={item.id} value={item.code}>{item.code} — {item.designation}</option>)}</select></label><label>Année<select aria-label="Année" value={year} onChange={(event) => { setYear(event.target.value); setPage(1) }}><option value="">Toutes</option>{years.map((item) => <option key={item}>{item}</option>)}</select></label><label>Mois<select aria-label="Mois" value={month} onChange={(event) => { setMonth(event.target.value); setPage(1) }}><option value="">Tous les mois</option>{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={index + 1}>{new Intl.DateTimeFormat('fr-FR', { month: 'long' }).format(new Date(Date.UTC(2026, index, 1)))}</option>)}</select></label><label>Rechercher un indice<input aria-label="Rechercher un indice" value={code} placeholder="Code ou désignation" onChange={(event) => { setCode(event.target.value); setPage(1) }} /></label><label>Statut<select aria-label="Statut" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}><option value="">Tous</option><option value="DEFINITIVE">Définitif</option><option value="PENDING_VALIDATION">En attente de validation</option></select></label></div><button className="primary" type="button" onClick={() => load(1)}>Filtrer</button></div>
    {preview && <div className="card index-import-preview"><div className="section-heading"><div><p className="eyebrow">PRÉVISUALISATION</p><h2>{preview.year && preview.month ? monthLabel(preview.year, preview.month) : 'Barème'}</h2></div><span className="badge">{preview.validation_status}</span></div><p><strong>Fichier :</strong> {preview.filename} · <strong>SHA256 :</strong> {preview.sha256}</p><p><strong>Indices détectés :</strong> {preview.count} · <strong>Anomalies bloquantes :</strong> {preview.blocking_issues}</p><div className="table-scroll"><table><thead><tr><th>Code</th><th>Désignation</th><th>Valeur extraite</th><th>Valeur locale</th><th>État</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.id}><td>{row.status === 'AMBIGUOUS' ? <span><select aria-label={`Résoudre ${row.raw_extracted_code}`} value="" disabled={busy} onChange={(event) => resolveRow(row.id, event.target.value)}><option value="">{row.raw_extracted_code || '?'} — choisir</option>{definitions.filter((item) => row.resolution_candidates.length === 0 || row.resolution_candidates.includes(item.code)).map((item) => <option key={item.id} value={item.id}>{item.code} — {item.designation}</option>)}</select><input aria-label={`Nouveau code ${row.raw_extracted_code}`} placeholder="Code corrigé" value={correctedCodes[row.id] || ''} onChange={(event) => setCorrectedCodes({ ...correctedCodes, [row.id]: event.target.value })} /><button type="button" disabled={busy || !correctedCodes[row.id]} onClick={() => createDefinition(row.id, correctedCodes[row.id])}>Créer</button></span> : row.status === 'NEW_OFFICIAL_CODE' ? <span><strong>{row.code}</strong><input aria-label={`Désignation ${row.code}`} placeholder="Désignation (facultative)" value={newDesignations[row.id] || ''} disabled={busy} onChange={(event) => setNewDesignations({ ...newDesignations, [row.id]: event.target.value })} /><button type="button" disabled={busy} onClick={() => createDefinition(row.id)}>Créer</button></span> : row.code}</td><td>{row.designation}</td><td>{row.value ? formatDecimal(row.value) : '—'}</td><td>{row.local_value ? formatDecimal(row.local_value) : '—'}</td><td><span className="badge">{row.status}{row.resolution_method?.startsWith('MANUAL') ? ' · MANUEL' : ''}</span></td></tr>)}</tbody></table></div><button className="primary" type="button" disabled={busy || preview.blocking_issues > 0 || preview.validation_status === 'VALIDATED'} onClick={validate}>Valider le barème</button></div>}
    <div className="section-heading"><div><p className="eyebrow">BASE DES INDICES</p><h2>Valeurs stockées localement</h2></div><span className="muted">{pageInfo.count} valeur(s)</span></div><div className="table-scroll card"><table><thead><tr><th>Indice</th><th>Désignation</th><th>Mois</th><th>Année</th><th>Valeur</th><th>Statut</th></tr></thead><tbody>{values.map((item) => <tr key={item.id}><td>{item.index_definition_detail.code}</td><td>{item.index_definition_detail.designation}</td><td>{monthLabel(item.year, item.month).split(' ')[0]}</td><td>{item.year}</td><td>{formatDecimal(item.value)}</td><td><span className="badge">{statusLabel[item.status] || item.status}</span></td></tr>)}</tbody></table>{values.length === 0 && <p className="state">Aucun indice ne correspond aux filtres.</p>}<div className="pagination-controls"><button type="button" disabled={!pageInfo.has_previous} onClick={() => load(page - 1)}>Précédent</button><span>Page {page} · {pageInfo.count} valeur(s)</span><button type="button" disabled={!pageInfo.has_next} onClick={() => load(page + 1)}>Suivant</button></div></div>
    <div className="section-heading"><div><p className="eyebrow">BARÈMES OFFICIELS</p><h2>Historique documentaire</h2></div></div><div className="company-list">{publications.map((publication) => <div className="card company-row" key={publication.id}><div><strong>{monthLabel(publication.year, publication.month)}</strong><span>{publication.document_reference} · {methodLabel[publication.import_method] || publication.import_method}</span><span>{publication.indices_count} indice(s) · SHA256 : {publication.document_hash || '—'}</span>{details === publication.id && <span>Page officielle : {publication.source_page_url || 'Import manuel'} · PDF : {publication.source_pdf_url || '—'}</span>}</div><div><span className="badge">{publication.status}</span><span>Importé le {new Date(publication.imported_at).toLocaleDateString('fr-FR')} · Validé le {publication.validated_at ? new Date(publication.validated_at).toLocaleDateString('fr-FR') : '—'}</span><button type="button" onClick={() => setDetails(details === publication.id ? null : publication.id)}>{details === publication.id ? 'Masquer' : 'Voir'}</button></div></div>)}</div>
  </section>
}
