import { useEffect, useMemo, useState } from 'react'
import { ApiError, ExternalIndexStaging, IndexPublication, MonthlyIndexValue, listExternalIndexStaging, listIndexPublications, listIndexValues } from '../lib/api'

const monthLabel = (year: number, month: number) => new Intl.DateTimeFormat('fr-FR', { month: 'long', year: 'numeric' }).format(new Date(Date.UTC(year, month - 1, 1)))
const statusLabel: Record<string, string> = { DEFINITIVE: 'VALIDÉ', PROVISIONAL: 'PROVISOIRE', PENDING_VALIDATION: 'EN ATTENTE' }
const sourceTypeLabel: Record<string, string> = { OFFICIAL: 'OFFICIEL', EXTERNAL_SECONDARY: 'EXTERNE', MANUAL_VALIDATED: 'VALIDATION MANUELLE' }

export function IndicesPage() {
  const [values, setValues] = useState<MonthlyIndexValue[]>([]); const [publications, setPublications] = useState<IndexPublication[]>([]); const [staging, setStaging] = useState<ExternalIndexStaging[]>([]); const [stagingPage, setStagingPage] = useState({ page: 1, count: 0, has_next: false })
  const [year, setYear] = useState(''); const [month, setMonth] = useState(''); const [code, setCode] = useState(''); const [domain, setDomain] = useState(''); const [status, setStatus] = useState(''); const [error, setError] = useState('')
  const load = (requestedPage = 1) => {
    const params = new URLSearchParams(); if (year) params.set('year', year); if (month) params.set('month', month); if (code) params.set('code', code); if (domain) params.set('domain', domain); if (status) params.set('status', status)
    const stagingParams = new URLSearchParams(); if (year) stagingParams.set('year', year); if (month) stagingParams.set('month', month); if (code) stagingParams.set('external_code', code); if (status) stagingParams.set('comparison_status', status); stagingParams.set('page', String(requestedPage)); stagingParams.set('page_size', '50')
    Promise.all([listIndexValues(params.toString()), listIndexPublications(), listExternalIndexStaging(stagingParams.toString())]).then(([loaded, loadedPublications, loadedStaging]) => { setValues(loaded); setPublications(loadedPublications); setStaging(loadedStaging.results); setStagingPage({ page: loadedStaging.page, count: loadedStaging.count, has_next: loadedStaging.has_next }) }).catch((caught) => setError(caught instanceof ApiError ? caught.payload.message : 'Erreur réseau. Réessayez.'))
  }
  useEffect(() => { load() }, [])
  const domains = useMemo(() => Array.from(new Set(values.map((item) => item.index_definition_detail.domain).filter(Boolean))), [values])
  const detailCode = code || values[0]?.index_definition_detail.code
  const detailValues = values.filter((item) => item.index_definition_detail.code === detailCode).sort((left, right) => left.year - right.year || left.month - right.month)
  const graphPoints = useMemo(() => { const numbers = detailValues.map((item) => Number(item.value)); const min = Math.min(...numbers); const max = Math.max(...numbers); return detailValues.map((item, index) => `${index * 100},${100 - ((Number(item.value) - min) / (max - min || 1)) * 80}`).join(' ') }, [detailValues])
  return <section>
    <div className="page-heading"><div><p className="eyebrow">RÉFÉRENTIEL DES INDICES</p><h1>Indices / Barèmes</h1><p className="muted">La valeur API externe reste distincte de la valeur validée par publication officielle.</p></div></div>{error && <div className="alert error">{error}</div>}
    <div className="card company-form"><div className="form-grid"><label>Année<input value={year} placeholder="2025" onChange={(event) => setYear(event.target.value)} /></label><label>Mois<select value={month} onChange={(event) => setMonth(event.target.value)}><option value="">Tous</option>{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={index + 1}>{index + 1}</option>)}</select></label><label>Code<input value={code} placeholder="BAT3" onChange={(event) => setCode(event.target.value)} /></label><label>Famille<select value={domain} onChange={(event) => setDomain(event.target.value)}><option value="">Toutes</option>{domains.map((item) => <option key={item}>{item}</option>)}</select></label><label>Statut<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Tous</option><option value="MATCHED">Correspondant</option><option value="CONFLICT">Conflit</option><option value="MISSING_LOCAL">Local manquant</option><option value="INVALID">Invalide</option><option value="PENDING_VALIDATION">Validation en attente</option></select></label></div><button className="primary" type="button" onClick={() => load(1)}>Filtrer</button></div>
    <div className="section-heading"><div><p className="eyebrow">SYNCHRONISATION EXTERNE</p><h2>Indices externes / Synchronisation</h2></div></div>{staging.length === 0 ? <div className="card state">Aucune donnée de staging.</div> : <><div className="company-list">{staging.map((item) => <div className={`card company-row ${item.comparison_status === 'CONFLICT' ? 'staging-conflict' : ''}`} key={item.id}><div><strong>{item.external_code}{item.external_designation ? ` — ${item.external_designation}` : ''}</strong><span>{item.year && item.month ? monthLabel(item.year, item.month) : 'Catalogue'} · EXTERNE : {item.source_provider}</span><span>Récupéré le : {new Date(item.retrieved_at).toLocaleString('fr-FR')}</span></div><div><strong>{item.normalized_value ?? '—'}</strong><span>Local : {item.local_value ?? '—'}</span><span className="badge">{item.comparison_status} · {item.validation_status}</span></div></div>)}</div><div className="pagination-controls"><button type="button" disabled={stagingPage.page <= 1} onClick={() => load(stagingPage.page - 1)}>Précédent</button><span>Page {stagingPage.page} · {stagingPage.count} lignes</span><button type="button" disabled={!stagingPage.has_next} onClick={() => load(stagingPage.page + 1)}>Suivant</button></div></>}
    <div className="section-heading"><div><p className="eyebrow">PUBLICATIONS</p><h2>Barèmes et provenance</h2></div></div><div className="company-list">{publications.map((publication) => <div className="card company-row" key={publication.id}><div><strong>{monthLabel(publication.year, publication.month)}</strong><span>{publication.document_reference} · {sourceTypeLabel[publication.source_type] || publication.source_type}</span><span>SHA256 : {publication.document_hash || '—'}</span></div><span className="badge">{publication.status === 'VALIDATED' ? 'VALIDÉ' : 'EN ATTENTE'}</span></div>)}</div>
    <div className="section-heading"><div><p className="eyebrow">VALEURS MENSUELLES</p><h2>Indices locaux</h2></div></div>{values.length === 0 ? <div className="card state">Aucun indice ne correspond aux filtres.</div> : <div className="company-list">{values.map((item) => <div className="card company-row" key={item.id}><div><strong>{item.index_definition_detail.code} — {item.index_definition_detail.designation}</strong><span>{monthLabel(item.year, item.month)} · {item.index_definition_detail.domain || 'Famille non renseignée'}</span><span>Publication : {item.publication_detail.document_reference}</span><span>Source : {sourceTypeLabel[item.publication_detail.source_type] || item.publication_detail.source_type} · validé le {item.validated_at ? new Date(item.validated_at as string).toLocaleDateString('fr-FR') : '—'}</span></div><div><strong>{item.value}</strong><span className="badge">{statusLabel[item.status] || item.status}</span> <span className="badge">{sourceTypeLabel[item.publication_detail.source_type] || item.publication_detail.source_type}</span></div></div>)}</div>}
    {detailValues.length > 0 && <div className="card index-detail"><div className="section-heading"><div><p className="eyebrow">FICHE INDICE</p><h2>{detailCode} — {detailValues[0].index_definition_detail.designation}</h2></div></div><svg className="index-chart" role="img" aria-label={`Évolution ${detailCode}`} viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={graphPoints} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke" /></svg><div className="table-scroll"><table><thead><tr><th>Code</th><th>Mois</th><th>Valeur</th><th>Statut</th><th>Source</th><th>Publication</th></tr></thead><tbody>{detailValues.map((item) => <tr key={item.id}><td>{item.index_definition_detail.code}</td><td>{monthLabel(item.year, item.month)}</td><td>{item.value}</td><td><span className="badge">{statusLabel[item.status] || item.status}</span></td><td>{sourceTypeLabel[item.publication_detail.source_type] || item.publication_detail.source_type}</td><td>{item.publication_detail.document_reference}</td></tr>)}</tbody></table></div><p className="muted">Évolution locale PostgreSQL : {detailValues[0].value} → {detailValues[detailValues.length - 1].value}. Validation : {detailValues[detailValues.length - 1].validated_at ? new Date(detailValues[detailValues.length - 1].validated_at as string).toLocaleDateString('fr-FR') : 'en attente'}.</p></div>}
  </section>
}
